update ci config

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -61,30 +61,40 @@ sonarcloud-check:
 
 deploy:
   stage: deploy
-  image: alpine:latest
+  image: curlimages/curl:latest
   script:
-    - apk update && apk add --no-cache curl jq
-    - curl --version
-    - jq --version
+    - echo "Iniciando despliegue en Render..."
     - |
-      DEPLOY_RESPONSE=$(curl -s -H "Authorization: Bearer ${RENDER_API_KEY}" "https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys/${DEPLOY_ID}")
-      echo "Respuesta del webhook: $DEPLOY_RESPONSE"
-      DEPLOY_STATUS=$(echo $DEPLOY_RESPONSE | jq -r '.status')
-
-      if [ "$DEPLOY_STATUS" == "null" ] || [ -z "$DEPLOY_STATUS" ]; then
-        echo "Error: No se pudo obtener el estado del despliegue. Respuesta incompleta."
+      # Solicitar el despliegue
+      DEPLOY_RESPONSE=$(curl -s -X POST "https://api.render.com/deploy/${RENDER_SERVICE_ID}?key=${RENDER_API_KEY}")
+      echo "Respuesta del webhook de despliegue: $DEPLOY_RESPONSE"
+      
+      # Extraer el ID del despliegue desde la respuesta
+      DEPLOY_ID=$(echo $DEPLOY_RESPONSE | jq -r '.deploy.id')
+      echo "ID del despliegue: $DEPLOY_ID"
+      
+      if [ "$DEPLOY_ID" == "null" ] || [ -z "$DEPLOY_ID" ]; then
+        echo "Error: No se pudo obtener el ID del despliegue."
         exit 1
       fi
 
-      echo "Estado del despliegue: $DEPLOY_STATUS"
-      if [ "$DEPLOY_STATUS" == "live" ]; then
-        echo "El despliegue fue exitoso."
-      elif [ "$DEPLOY_STATUS" == "failed" ]; then
-        echo "El despliegue falló."
-        exit 1
-      else
-        echo "El estado del despliegue es: $DEPLOY_STATUS"
-      fi
+      # Consultar el estado del despliegue
+      echo "Esperando a que finalice el despliegue..."
+      while true; do
+        DEPLOY_STATUS=$(curl -s "https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys/$DEPLOY_ID" | jq -r '.status')
+        echo "Estado del despliegue: $DEPLOY_STATUS"
+        
+        if [ "$DEPLOY_STATUS" == "live" ]; then
+          echo "El despliegue fue exitoso."
+          break
+        elif [ "$DEPLOY_STATUS" == "failed" ]; then
+          echo "El despliegue falló."
+          exit 1
+        else
+          echo "Esperando 10 segundos antes de volver a verificar..."
+          sleep 10
+        fi
+      done
   only:
     - main
   when: on_success
